# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u5168\u79f0')),
                ('address', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='\u7535\u8bdd')),
            ],
        ),
    ]
