# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('arturnover', models.FloatField(verbose_name='\u5e94\u6536\u8d26\u6b3e\u5468\u8f6c\u7387(\u6b21)')),
                ('arturndays', models.FloatField(verbose_name='\u5e94\u6536\u8d26\u6b3e\u5468\u8f6c\u5929\u6570(\u5929)')),
                ('inventory_turnover', models.FloatField(verbose_name='\u5b58\u8d27\u5468\u8f6c\u7387(\u6b21)')),
                ('inventory_days', models.FloatField(verbose_name='\u5b58\u8d27\u5468\u8f6c\u5929\u6570(\u5929)')),
                ('currentasset_turnover', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7\u5468\u8f6c\u7387(\u6b21)')),
                ('currentasset_days', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7\u5468\u8f6c\u5929\u6570(\u5929)')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('roe', models.FloatField(verbose_name='\u51c0\u8d44\u4ea7\u6536\u76ca\u7387(%)')),
                ('net_profit_ratio', models.FloatField(verbose_name='\u51c0\u5229\u7387(%)')),
                ('gross_profit_rate', models.FloatField(verbose_name='\u6bdb\u5229\u7387(%)')),
                ('net_profits', models.FloatField(verbose_name='\u51c0\u5229\u6da6(\u4e07\u5143)')),
                ('esp', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('business_income', models.FloatField(verbose_name='\u8425\u4e1a\u6536\u5165(\u767e\u4e07\u5143)')),
                ('bips', models.FloatField(verbose_name='\u6bcf\u80a1\u4e3b\u8425\u4e1a\u52a1\u6536\u5165(\u5143)')),
            ],
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('esp', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('eps_yoy', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca\u540c\u6bd4( %)')),
                ('bvps', models.FloatField(verbose_name='\u6bcf\u80a1\u51c0\u8d44\u4ea7')),
                ('roe', models.FloatField(verbose_name='\u51c0\u8d44\u4ea7\u6536\u76ca\u7387( %)')),
                ('epcf', models.FloatField(verbose_name='\u6bcf\u80a1\u73b0\u91d1\u6d41\u91cf(\u5143)')),
                ('net_profits', models.FloatField(verbose_name='\u51c0\u5229\u6da6(\u4e07\u5143)')),
                ('profits_yoy', models.FloatField(verbose_name='\u51c0\u5229\u6da6\u540c\u6bd4( %)')),
                ('distrib', models.FloatField(verbose_name='\u5206\u914d\u65b9\u6848')),
                ('report_date', models.CharField(max_length=20, verbose_name='\u53d1\u5e03\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='StockBasics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('industry', models.CharField(max_length=50, verbose_name='\u6240\u5c5e\u884c\u4e1a')),
                ('area', models.CharField(max_length=20, verbose_name='\u5730\u533a')),
                ('pe', models.FloatField(verbose_name='\u5e02\u76c8\u7387')),
                ('outstanding', models.FloatField(verbose_name='\u6d41\u901a\u80a1\u672c(\u4ebf)')),
                ('totals', models.FloatField(verbose_name='\u603b\u80a1\u672c(\u4ebf)')),
                ('totalAssets', models.FloatField(verbose_name='\u603b\u8d44\u4ea7(\u4e07)')),
                ('liquidAssets', models.FloatField(verbose_name='\u6d41\u52a8\u8d44\u4ea7')),
                ('fixedAssets', models.FloatField(verbose_name='\u56fa\u5b9a\u8d44\u4ea7')),
                ('reserved', models.FloatField(verbose_name='\u516c\u79ef\u91d1')),
                ('reservedPerShare', models.FloatField(verbose_name='\u6bcf\u80a1\u516c\u79ef\u91d1')),
                ('esp', models.FloatField(verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('bvps', models.FloatField(verbose_name='\u6bcf\u80a1\u51c0\u8d44')),
                ('pb', models.FloatField(verbose_name='\u5e02\u51c0\u7387')),
                ('timeToMarket', models.CharField(max_length=20, verbose_name='\u4e0a\u5e02\u65e5\u671f')),
                ('undp', models.FloatField(verbose_name='\u672a\u5206\u5229\u6da6')),
                ('perundp', models.FloatField(verbose_name='\u6bcf\u80a1\u672a\u5206\u914d')),
                ('rev', models.FloatField(verbose_name='\u6536\u5165\u540c\u6bd4(%)')),
                ('profit', models.FloatField(verbose_name='\u5229\u6da6\u540c\u6bd4(%)')),
                ('gpr', models.FloatField(verbose_name='\u6bdb\u5229\u7387(%)')),
                ('npr', models.FloatField(verbose_name='\u51c0\u5229\u6da6\u7387(%)')),
                ('holders', models.FloatField(verbose_name='\u80a1\u4e1c\u4eba\u6570')),
            ],
        ),
    ]
